---
app_name: "oanda-test"
api_token: "/oanda/key"
account_id: "/oanda/account"
topic: "oanda-test-topic-aud_usd"
bootstrap_servers:
  - "b-1.oanda-test.8zyfgp.c4.kafka.ap-southeast-2.amazonaws.com:9092"
  - "b-2.oanda-test.8zyfgp.c4.kafka.ap-southeast-2.amazonaws.com:9092"
instruments:
  - "AUD_USD"
