---
app_name: "oanda-test"
region: "ap-southeast-2"
api_token: "/oanda/key"
account_id: "/oanda/account"
instruments:
  - "AUD_USD"
schema:
  name: instrument
  version: 1
kafka:
  topic: "oanda-test-topic-aud_usd"
  protocol: "SSL"
  protocol_version:
    major: 1
    minor: 0
    patch: 0
